#! /usr/bin/env sh

pandoc=""

while [ "$1" != "" ]; do
    case $1 in
	-P )         shift
		     pandoc="{.\2 name=\1.\2 caption=\1.\2 numbers=left frame=leftline}"
		     ;;
	*)           break
    esac
done
		     
sed -e "s/^<<\(.*\)\.\(.*\)>>= *$/~~~$pandoc/" -e 's/^@/~~~/' $*
