#! /usr/bin/env sh

while [ "$1" != "" ]; do
    case $1 in
	-R )         shift
		     filename=`echo "$1" | sed -e 's/\./\\\./g' -e 's|\/|\\\/|g'`
		     shift
		     ;;
	*)           break
    esac
done
		     
sed -e 's/^<<\(.*\)\.\(.*\)>>= *$/~~~{.\2 name=\1.\2 caption=\1.\2 numbers=left frame=leftline}/' -e 's/^@/~~~/' $*
